@app_url = http://127.0.0.1
@app_port = 8011
@chat_endpoint = /chat

# POST @{{app_url}}:{{app_port}}{{chat_endpoint}} HTTP/1.1
POST http://localhost:8011/chat
Content-Type: application/json

{"model": "llama3:latest", "prompt": "Give me 1 advice for the day."}

### llm request
POST http://localhost:11434/api/generate
Content-Type: application/json

{
    "model": "llama3:latest", 
    "prompt": "Give me 2 top health tips.",
    "stream": true
}